event_inherited();
rango = 60;
danio = 10;
cooldown = 40;
color_placeholder = c_red;
spr_up = Spr_TripleT_Up;
spr_down = Spr_TripleT_Down;
spr_left = Spr_TripleT_Left;
spr_right = Spr_TripleT_Right;
sprite_index = spr_down;
